- hosts: webservers
  vars:
    ansible_python_interpreter: /usr/bin/python3
 
  tasks:
    - name: just display
      shell: uptime
      register: hostname
    - debug:
        var: hostname
    
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
