---
- name: Install nginx
  hosts: webservers
  become: true

  tasks:
  - name: Add epel-release repo
    apt:
      name: epel-release
      state: present

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started
